=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

module Helo
  class APIError < StandardError
    attr_reader :code, :response_headers, :response_body

    # Usage examples:
    #   APIError.new
    #   APIError.new("message")
    #   APIError.new(:code => 500, :response_headers => {}, :response_body => "")
    #   APIError.new(:code => 404, :message => "Not Found")
    def initialize(arg = nil)
      if arg.is_a? Hash
        if arg.key?(:message) || arg.key?("message")
          super(arg[:message] || arg["message"])
        else
          super arg
        end

        arg.each do |k, v|
          instance_variable_set "@#{k}", v
        end
      else
        super arg
        @message = arg
      end
    end

    # Override to_s to display a friendly error message
    def to_s
      message
    end

    def detail
      json_response.fetch(:detail, [ "API Error", code, @message ].compact.join(" - "))
    end

    def errors
      json_response
        .fetch(:errors, {})
        .transform_keys(&:to_s)
    end

    def message
      if @message.nil?
        msg = "Error message: the server returns an error"
      else
        msg = @message
      end

      msg += "\nHTTP status code: #{code}" if code
      msg += "\nResponse headers: #{response_headers}" if response_headers
      msg += "\nResponse body: #{response_body}" if response_body

      msg
    end

    private

    def json_response
      @_json_response ||= parse_json
    end

    def parse_json
      JSON.parse(response_body.to_s, symbolize_names: true)
    rescue JSON::ParserError
      {}
    end
  end
end
