=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require "spec_helper"
require "json"

# Unit tests for Helo::ActivityAPI
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "ActivityAPI" do
  before do
    # run before each test
    @api_instance = Helo::ActivityAPI.new
  end

  after do
    # run after each test
  end

  describe "test an instance of ActivityAPI" do
    it "should create an instance of ActivityAPI" do
      expect(@api_instance).to be_instance_of(Helo::ActivityAPI)
    end
  end

  # unit tests for list_events
  # List activity events
  # Retrieves activity events for messages, including delivery status, opens, clicks, bounces, and complaints.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :channel_id
  # @option opts [String] :message_id
  # @option opts [Integer] :after
  # @option opts [Time] :start_date
  # @option opts [Time] :end_date
  # @option opts [Integer] :limit
  # @return [EventsResponse]
  describe "list_events test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_messages
  # List messages
  # Retrieves a paginated list of sent messages with basic tracking information.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :channel_id
  # @option opts [Integer] :after
  # @option opts [Time] :start_date
  # @option opts [Time] :end_date
  # @option opts [Integer] :limit
  # @option opts [String] :recipient
  # @option opts [String] :subject
  # @option opts [String] :tag
  # @option opts [String] :status
  # @return [MessagesResponse]
  describe "list_messages test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_message
  # Retrieve message details
  # Fetches detailed tracking information for a specific message, including all associated events.
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [MessageDetailsResponse]
  describe "retrieve_message test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
