=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require "spec_helper"
require "json"

# Unit tests for Helo::BroadcastsAPI
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "BroadcastsAPI" do
  before do
    # run before each test
    @api_instance = Helo::BroadcastsAPI.new
  end

  after do
    # run after each test
  end

  describe "test an instance of BroadcastsAPI" do
    it "should create an instance of BroadcastsAPI" do
      expect(@api_instance).to be_instance_of(Helo::BroadcastsAPI)
    end
  end

  # unit tests for list
  # List broadcasts
  # Retrieves a paginated list of sent broadcasts with summary statistics.
  # @param channel_id
  # @param [Hash] opts the optional parameters
  # @option opts [BroadcastStatus] :status
  # @option opts [String] :subject
  # @option opts [Integer] :limit
  # @option opts [Integer] :offset
  # @return [PaginatedResponseOfBroadcastResponse]
  describe "list test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_failures
  # List broadcast failures
  # Retrieves a list of failed messages for a specific broadcast.
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [BroadcastFailuresResponse]
  describe "list_failures test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_suppressions
  # List broadcast suppressions
  # Retrieves a list of suppressed recipients for a specific broadcast.
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [BroadcastSuppressionsResponse]
  describe "list_suppressions test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve
  # Retrieve a broadcast
  # Fetches details and statistics for a specific broadcast.
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [BroadcastDetailsResponse]
  describe "retrieve test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
