=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require "spec_helper"
require "json"

# Unit tests for Helo::ChannelsAPI
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "ChannelsAPI" do
  before do
    # run before each test
    @api_instance = Helo::ChannelsAPI.new
  end

  after do
    # run after each test
  end

  describe "test an instance of ChannelsAPI" do
    it "should create an instance of ChannelsAPI" do
      expect(@api_instance).to be_instance_of(Helo::ChannelsAPI)
    end
  end

  # unit tests for create
  # Create a channel
  # Creates a new communication channel for organizing and routing messages.
  # @param create_channel_request
  # @param [Hash] opts the optional parameters
  # @return [ChannelResponse]
  describe "create test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete
  # Delete a channel
  # Permanently removes a channel and all associated data.
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "delete test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list
  # List all channels
  # Retrieves a list of all channels accessible to the current user.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit
  # @option opts [Integer] :offset
  # @option opts [String] :name
  # @option opts [Array<String>] :channel_ids
  # @option opts [String] :delivery_type
  # @return [PaginationResultOfChannelResponse]
  describe "list test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve
  # Retrieve a channel
  # Fetches the details and configuration of a specific channel.
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [ChannelResponse]
  describe "retrieve test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update
  # Update a channel
  # Modifies the settings and configuration of an existing channel.
  # @param id
  # @param update_channel_request
  # @param [Hash] opts the optional parameters
  # @return [ChannelResponse]
  describe "update test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
