=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require "spec_helper"
require "json"

# Unit tests for Helo::DomainsAPI
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "DomainsAPI" do
  before do
    # run before each test
    @api_instance = Helo::DomainsAPI.new
  end

  after do
    # run after each test
  end

  describe "test an instance of DomainsAPI" do
    it "should create an instance of DomainsAPI" do
      expect(@api_instance).to be_instance_of(Helo::DomainsAPI)
    end
  end

  # unit tests for create
  # Create a domain
  # Registers a new domain for sending emails. The domain must be verified before it can be used.
  # @param create_domain_request
  # @param [Hash] opts the optional parameters
  # @return [DomainWithDnsResponse]
  describe "create test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete
  # Delete a domain
  # Removes a domain from the account. This will stop all email sending from this domain.
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "delete test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list
  # List all domains
  # Retrieves all domains associated with the current account, including their verification status.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit
  # @option opts [Integer] :offset
  # @option opts [String] :name
  # @option opts [Array<String>] :channel_ids
  # @return [PaginatedResponseOfDomainResponse]
  describe "list test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve
  # Retrieve a domain
  # Gets detailed information about a specific domain, including verification status and configuration.
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [DomainWithDnsResponse]
  describe "retrieve test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for rotate_key
  # Rotate a domain key
  # Generates new DKIM keys for the domain. This is recommended for security best practices.
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [DnsRecordResponse]
  describe "rotate_key test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update
  # Update a domain
  # Modifies the configuration settings of an existing domain.
  # @param id
  # @param update_domain_request
  # @param [Hash] opts the optional parameters
  # @return [DomainResponse]
  describe "update test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for verify
  # Verify a domain
  # Initiates the domain verification process by checking DNS records.
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [DnsRecordsResponse]
  describe "verify test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
