=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require "spec_helper"
require "json"

# Unit tests for Helo::SendingAPI
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "SendingAPI" do
  before do
    # run before each test
    @api_instance = Helo::SendingAPI.new
  end

  after do
    # run after each test
  end

  describe "test an instance of SendingAPI" do
    it "should create an instance of SendingAPI" do
      expect(@api_instance).to be_instance_of(Helo::SendingAPI)
    end
  end

  # unit tests for broadcast
  # Send a broadcast email
  # Sends a broadcast email to multiple recipients for marketing or announcement purposes.
  # @param send_broadcast_request
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_helo_channel_id Used to specify a channel ID when using a global (i.e. not channel-scoped) API credential.
  # @return [SendBroadcastResponse]
  describe "broadcast test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for broadcast_message
  # Send a single broadcast email
  # Sends a single broadcast email message.
  # @param send_message_request
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_helo_channel_id Used to specify a channel ID when using a global (i.e. not channel-scoped) API credential.
  # @return [SendMessageAcceptedResponse]
  describe "broadcast_message test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for transactional
  # Send a transactional email
  # Sends a single transactional email such as receipts, confirmations, or notifications.
  # @param send_message_request
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_helo_channel_id Used to specify a channel ID when using a global (i.e. not channel-scoped) API credential.
  # @return [SendMessageAcceptedResponse]
  describe "transactional test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for transactional_batch
  # Send transactional emails in batch
  # Sends multiple transactional emails in a single API request for better performance.
  # @param send_message_batch_request
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_helo_channel_id Used to specify a channel ID when using a global (i.e. not channel-scoped) API credential.
  # @return [SendMessageBatchResponse]
  describe "transactional_batch test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
