=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require "spec_helper"
require "json"

# Unit tests for Helo::StatisticsAPI
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "StatisticsAPI" do
  before do
    # run before each test
    @api_instance = Helo::StatisticsAPI.new
  end

  after do
    # run after each test
  end

  describe "test an instance of StatisticsAPI" do
    it "should create an instance of StatisticsAPI" do
      expect(@api_instance).to be_instance_of(Helo::StatisticsAPI)
    end
  end

  # unit tests for retrieve_daily
  # Retrieve daily statistics
  # Fetches daily aggregated statistics.
  # @param from
  # @param to
  # @param timezone
  # @param [Hash] opts the optional parameters
  # @option opts [String] :channel_id
  # @option opts [String] :tag
  # @return [StatisticsResponse]
  describe "retrieve_daily test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_hourly
  # Retrieve hourly statistics
  # Fetches hourly aggregated statistics.
  # @param from
  # @param to
  # @param [Hash] opts the optional parameters
  # @option opts [String] :channel_id
  # @option opts [String] :tag
  # @return [StatisticsResponse]
  describe "retrieve_hourly test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_totals
  # Retrieve all time statistics
  # Fetches cumulative statistics.
  # @param from
  # @param to
  # @param [Hash] opts the optional parameters
  # @option opts [String] :channel_id
  # @option opts [String] :tag
  # @return [StatisticsTotalsResponse]
  describe "retrieve_totals test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
