=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require "spec_helper"
require "json"

# Unit tests for Helo::SuppressionsAPI
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "SuppressionsAPI" do
  before do
    # run before each test
    @api_instance = Helo::SuppressionsAPI.new
  end

  after do
    # run after each test
  end

  describe "test an instance of SuppressionsAPI" do
    it "should create an instance of SuppressionsAPI" do
      expect(@api_instance).to be_instance_of(Helo::SuppressionsAPI)
    end
  end

  # unit tests for create
  # Create suppressions
  # Adds email addresses to the suppression list to prevent future sends.
  # @param create_suppressions_request
  # @param [Hash] opts the optional parameters
  # @return [CreateSuppressionsResponse]
  describe "create test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list
  # List suppressions
  # Retrieves a list of suppressed email addresses for a channel.
  # @param channel_id
  # @param mail_type
  # @param [Hash] opts the optional parameters
  # @option opts [SuppressionReason] :reason
  # @option opts [String] :email
  # @option opts [Integer] :limit
  # @option opts [Integer] :offset
  # @return [PaginatedResponseOfSuppressionResponse]
  describe "list test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove
  # Remove suppressions
  # Removes email addresses from the suppression list to allow future sends.
  # @param remove_suppressions_request
  # @param [Hash] opts the optional parameters
  # @return [RemoveSuppressionsResponse]
  describe "remove test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
