=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require "spec_helper"
require "json"

# Unit tests for Helo::WebhookEndpointsAPI
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "WebhookEndpointsAPI" do
  before do
    # run before each test
    @api_instance = Helo::WebhookEndpointsAPI.new
  end

  after do
    # run after each test
  end

  describe "test an instance of WebhookEndpointsAPI" do
    it "should create an instance of WebhookEndpointsAPI" do
      expect(@api_instance).to be_instance_of(Helo::WebhookEndpointsAPI)
    end
  end

  # unit tests for create
  # Create a webhook endpoint
  # Registers a new webhook endpoint to receive event notifications.
  # @param create_webhook_endpoint_request
  # @param [Hash] opts the optional parameters
  # @return [WebhookEndpointResponse]
  describe "create test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete
  # Delete a webhook endpoint
  # Permanently removes a webhook endpoint.
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "delete test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list
  # List all webhook endpoints
  # Retrieves all webhook endpoints configured for the account.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit
  # @option opts [Integer] :offset
  # @option opts [Array<String>] :channel_ids
  # @return [PaginationResultOfWebhookEndpointResponse]
  describe "list test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for regenerate_signing_key
  # Regenerate webhook signing key
  # Generates a new signing key for webhook payload verification.
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [WebhookEndpointResponse]
  describe "regenerate_signing_key test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve
  # Retrieve a webhook endpoint
  # Fetches the details and configuration of a specific webhook endpoint.
  # @param id
  # @param [Hash] opts the optional parameters
  # @return [WebhookEndpointResponse]
  describe "retrieve test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update
  # Update a webhook endpoint
  # Modifies the configuration of an existing webhook endpoint.
  # @param id
  # @param update_webhook_endpoint_request
  # @param [Hash] opts the optional parameters
  # @return [WebhookEndpointResponse]
  describe "update test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
