=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

# Common files
require "helo-ruby/api_client"
require "helo-ruby/api_error"
require "helo-ruby/version"
require "helo-ruby/configuration"

# Models
require "helo-ruby/models/attachment"
require "helo-ruby/models/attachment_disposition"
require "helo-ruby/models/broadcast_content"
require "helo-ruby/models/broadcast_content_attachments_inner"
require "helo-ruby/models/broadcast_content_template"
require "helo-ruby/models/broadcast_details_response"
require "helo-ruby/models/broadcast_failure_response"
require "helo-ruby/models/broadcast_response"
require "helo-ruby/models/broadcast_statistics"
require "helo-ruby/models/broadcast_status"
require "helo-ruby/models/broadcast_tracking"
require "helo-ruby/models/channel_response"
require "helo-ruby/models/create_channel_request"
require "helo-ruby/models/create_domain_request"
require "helo-ruby/models/create_suppressions_request"
require "helo-ruby/models/create_suppressions_response"
require "helo-ruby/models/create_webhook_endpoint_request"
require "helo-ruby/models/delivery_stats"
require "helo-ruby/models/delivery_type"
require "helo-ruby/models/dns_record_response"
require "helo-ruby/models/dns_record_status"
require "helo-ruby/models/dns_record_type"
require "helo-ruby/models/dns_records_response"
require "helo-ruby/models/domain_response"
require "helo-ruby/models/domain_with_dns_response"
require "helo-ruby/models/error_response"
require "helo-ruby/models/event_type"
require "helo-ruby/models/events_response"
require "helo-ruby/models/events_response_results_inner"
require "helo-ruby/models/mail_address"
require "helo-ruby/models/mail_address1"
require "helo-ruby/models/mail_type"
require "helo-ruby/models/message_details_response"
require "helo-ruby/models/message_details_response_events_inner"
require "helo-ruby/models/message_details_response_tracking"
require "helo-ruby/models/messages_response"
require "helo-ruby/models/messages_response_results_inner"
require "helo-ruby/models/paginated_response_of_broadcast"
require "helo-ruby/models/paginated_response_of_broadcast_failure"
require "helo-ruby/models/paginated_response_of_broadcast_suppression"
require "helo-ruby/models/paginated_response_of_domain_response"
require "helo-ruby/models/paginated_response_of_suppression_response"
require "helo-ruby/models/pagination_result_of_channel_response"
require "helo-ruby/models/pagination_result_of_webhook_endpoint_response"
require "helo-ruby/models/recipient_headers"
require "helo-ruby/models/remove_suppression_result"
require "helo-ruby/models/remove_suppressions_request"
require "helo-ruby/models/remove_suppressions_response"
require "helo-ruby/models/send_broadcast_request"
require "helo-ruby/models/send_broadcast_request_messages_inner"
require "helo-ruby/models/send_broadcast_request_template"
require "helo-ruby/models/send_broadcast_request_tracking"
require "helo-ruby/models/send_broadcast_response"
require "helo-ruby/models/send_message_accepted_response"
require "helo-ruby/models/send_message_batch_request"
require "helo-ruby/models/send_message_batch_response"
require "helo-ruby/models/send_message_failed_response"
require "helo-ruby/models/send_message_request"
require "helo-ruby/models/send_message_response"
require "helo-ruby/models/statistics_response"
require "helo-ruby/models/statistics_response_results_inner"
require "helo-ruby/models/statistics_totals_response"
require "helo-ruby/models/suppression_reason"
require "helo-ruby/models/suppression_response"
require "helo-ruby/models/suppression_result"
require "helo-ruby/models/update_channel_request"
require "helo-ruby/models/update_domain_request"
require "helo-ruby/models/update_webhook_endpoint_request"
require "helo-ruby/models/validation_error"
require "helo-ruby/models/webhook_endpoint_response"
require "helo-ruby/models/webhook_event"
require "helo-ruby/models/webhook_header"

# APIs
require "helo-ruby/api/activity_api"
require "helo-ruby/api/broadcasts_api"
require "helo-ruby/api/channels_api"
require "helo-ruby/api/domains_api"
require "helo-ruby/api/sending_api"
require "helo-ruby/api/statistics_api"
require "helo-ruby/api/suppressions_api"
require "helo-ruby/api/webhook_endpoints_api"

# Singletons
module Helo
  Activity = ActivityAPI.new
  Broadcasts = BroadcastsAPI.new
  Channels = ChannelsAPI.new
  Domains = DomainsAPI.new
  Sending = SendingAPI.new
  Statistics = StatisticsAPI.new
  Suppressions = SuppressionsAPI.new
  WebhookEndpoints = WebhookEndpointsAPI.new
end

module Helo
  class << self
    # Customize default settings for the SDK using block.
    #   Helo.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
