=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require "date"
require "time"

module Helo
  class AttachmentDisposition
    ATTACHMENT = "attachment".freeze
    INLINE = "inline".freeze

    def self.all_vars
      @all_vars ||= [ ATTACHMENT, INLINE ].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if AttachmentDisposition.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #AttachmentDisposition"
    end
  end
end
