=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require "date"
require "time"

module Helo
  class BroadcastDetailsResponse
    attr_accessor :id

    attr_accessor :created_at

    attr_accessor :status

    attr_accessor :subject

    attr_accessor :completion

    attr_accessor :messages

    attr_accessor :content

    attr_accessor :tracking

    attr_accessor :statistics

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        'id': :'id',
        'created_at': :'createdAt',
        'status': :'status',
        'subject': :'subject',
        'completion': :'completion',
        'messages': :'messages',
        'content': :'content',
        'tracking': :'tracking',
        'statistics': :'statistics'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        'id': :'String',
        'created_at': :'Time',
        'status': :'BroadcastStatus',
        'subject': :'String',
        'completion': :'String',
        'messages': :'Integer',
        'content': :'BroadcastContent',
        'tracking': :'BroadcastTracking',
        'statistics': :'BroadcastStatistics'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if !attributes.is_a?(Hash)
        fail ArgumentError, "The input argument (attributes) must be a hash in `Helo::BroadcastDetailsResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if !acceptable_attribute_map.key?(k.to_sym)
          fail ArgumentError, "`#{k}` is not a valid attribute in `Helo::BroadcastDetailsResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'subject')
        self.subject = attributes[:'subject']
      else
        self.subject = nil
      end

      if attributes.key?(:'completion')
        self.completion = attributes[:'completion']
      else
        self.completion = nil
      end

      if attributes.key?(:'messages')
        self.messages = attributes[:'messages']
      else
        self.messages = nil
      end

      if attributes.key?(:'content')
        self.content = attributes[:'content']
      else
        self.content = nil
      end

      if attributes.key?(:'tracking')
        self.tracking = attributes[:'tracking']
      else
        self.tracking = nil
      end

      if attributes.key?(:'statistics')
        self.statistics = attributes[:'statistics']
      else
        self.statistics = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn "[DEPRECATED] the `list_invalid_properties` method is obsolete"
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @subject.nil?
        invalid_properties.push('invalid value for "subject", subject cannot be nil.')
      end

      if @completion.nil?
        invalid_properties.push('invalid value for "completion", completion cannot be nil.')
      end

      if @messages.nil?
        invalid_properties.push('invalid value for "messages", messages cannot be nil.')
      end

      if @content.nil?
        invalid_properties.push('invalid value for "content", content cannot be nil.')
      end

      if @tracking.nil?
        invalid_properties.push('invalid value for "tracking", tracking cannot be nil.')
      end

      if @statistics.nil?
        invalid_properties.push('invalid value for "statistics", statistics cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn "[DEPRECATED] the `valid?` method is obsolete"
      return false if @id.nil?
      return false if @created_at.nil?
      return false if @status.nil?
      return false if @subject.nil?
      return false if @completion.nil?
      return false if @messages.nil?
      return false if @content.nil?
      return false if @tracking.nil?
      return false if @statistics.nil?
      true
    end

    # Attribute writer method
    # @param [Object] id Object to be assigned
    def id=(id)
      @id = id
    end

    # Attribute writer method
    # @param [Object] created_at Object to be assigned
    def created_at=(created_at)
      @created_at = created_at
    end

    # Attribute writer method
    # @param [Object] status Object to be assigned
    def status=(status)
      @status = status
    end

    # Attribute writer method
    # @param [Object] subject Object to be assigned
    def subject=(subject)
      @subject = subject
    end

    # Attribute writer method
    # @param [Object] completion Object to be assigned
    def completion=(completion)
      @completion = completion
    end

    # Attribute writer method
    # @param [Object] messages Object to be assigned
    def messages=(messages)
      @messages = messages&.to_i
    end

    # Attribute writer method
    # @param [Object] content Object to be assigned
    def content=(content)
      @content = content
    end

    # Attribute writer method
    # @param [Object] tracking Object to be assigned
    def tracking=(tracking)
      @tracking = tracking
    end

    # Attribute writer method
    # @param [Object] statistics Object to be assigned
    def statistics=(statistics)
      @statistics = statistics
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          created_at == o.created_at &&
          status == o.status &&
          subject == o.subject &&
          completion == o.completion &&
          messages == o.messages &&
          content == o.content &&
          tracking == o.tracking &&
          statistics == o.statistics
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [ id, created_at, status, subject, completion, messages, content, tracking, statistics ].hash
    end

    # Outputs specified attributes and their values as a hash
    # @param [Array] attributes Attributes to include in hash
    # @return [Hash] Attribute/value-pairs of specified attributes
    def slice(*attributes)
      attributes.to_h do |attribute|
        [ attribute, public_send(attribute) ]
      end
    end

    # Allows hash-like assignment syntax for setting attributes
    # @param [Symbol, String] attribute The attribute name to set
    # @param [Object] value The value to assign
    def []=(attribute, value)
      public_send("#{attribute}=", value)
    end

    # Allows hash-like access to attributes
    # @param [Symbol, String] attribute The attribute name to get
    def [](attribute)
      public_send(attribute)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Helo.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
