=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require "date"
require "time"

module Helo
  class EventType
    ACCEPTED = "accepted".freeze
    PROCESSED = "processed".freeze
    DELIVERED = "delivered".freeze
    BOUNCED = "bounced".freeze
    OPENED = "opened".freeze
    CLICKED = "clicked".freeze
    COMPLAINED = "complained".freeze
    UNSUBSCRIBED = "unsubscribed".freeze

    def self.all_vars
      @all_vars ||= [ ACCEPTED, PROCESSED, DELIVERED, BOUNCED, OPENED, CLICKED, COMPLAINED, UNSUBSCRIBED ].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if EventType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #EventType"
    end
  end
end
