=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require "date"
require "time"

module Helo
  class MessageDetailsResponse
    attr_accessor :message_id

    attr_accessor :channel_id

    attr_accessor :timestamp

    attr_accessor :mail_type

    attr_accessor :mail_source

    attr_accessor :delivery_type

    attr_accessor :status

    attr_accessor :subject

    attr_accessor :from

    attr_accessor :to

    attr_accessor :cc

    attr_accessor :bcc

    attr_accessor :reply_to

    attr_accessor :text

    attr_accessor :html

    attr_accessor :body

    attr_accessor :tags

    attr_accessor :headers

    attr_accessor :metadata

    attr_accessor :attachments

    attr_accessor :tracking

    attr_accessor :events

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        'message_id': :'messageId',
        'channel_id': :'channelId',
        'timestamp': :'timestamp',
        'mail_type': :'mailType',
        'mail_source': :'mailSource',
        'delivery_type': :'deliveryType',
        'status': :'status',
        'subject': :'subject',
        'from': :'from',
        'to': :'to',
        'cc': :'cc',
        'bcc': :'bcc',
        'reply_to': :'replyTo',
        'text': :'text',
        'html': :'html',
        'body': :'body',
        'tags': :'tags',
        'headers': :'headers',
        'metadata': :'metadata',
        'attachments': :'attachments',
        'tracking': :'tracking',
        'events': :'events'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        'message_id': :'String',
        'channel_id': :'String',
        'timestamp': :'Time',
        'mail_type': :'String',
        'mail_source': :'String',
        'delivery_type': :'String',
        'status': :'String',
        'subject': :'String',
        'from': :'MailAddress',
        'to': :'Array<MailAddress>',
        'cc': :'Array<MailAddress>',
        'bcc': :'Array<MailAddress>',
        'reply_to': :'Array<MailAddress>',
        'text': :'String',
        'html': :'String',
        'body': :'String',
        'tags': :'Array<String>',
        'headers': :'Object',
        'metadata': :'Object',
        'attachments': :'Array<String>',
        'tracking': :'MessageDetailsResponseTracking',
        'events': :'Array<MessageDetailsResponseEventsInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if !attributes.is_a?(Hash)
        fail ArgumentError, "The input argument (attributes) must be a hash in `Helo::MessageDetailsResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if !acceptable_attribute_map.key?(k.to_sym)
          fail ArgumentError, "`#{k}` is not a valid attribute in `Helo::MessageDetailsResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'message_id')
        self.message_id = attributes[:'message_id']
      else
        self.message_id = nil
      end

      if attributes.key?(:'channel_id')
        self.channel_id = attributes[:'channel_id']
      else
        self.channel_id = nil
      end

      if attributes.key?(:'timestamp')
        self.timestamp = attributes[:'timestamp']
      else
        self.timestamp = nil
      end

      if attributes.key?(:'mail_type')
        self.mail_type = attributes[:'mail_type']
      else
        self.mail_type = nil
      end

      if attributes.key?(:'mail_source')
        self.mail_source = attributes[:'mail_source']
      else
        self.mail_source = nil
      end

      if attributes.key?(:'delivery_type')
        self.delivery_type = attributes[:'delivery_type']
      else
        self.delivery_type = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'subject')
        self.subject = attributes[:'subject']
      else
        self.subject = nil
      end

      if attributes.key?(:'from')
        self.from = attributes[:'from']
      else
        self.from = nil
      end

      if attributes.key?(:'to')
        if (value = attributes[:'to']).is_a?(Array)
          self.to = value
        end
      else
        self.to = nil
      end

      if attributes.key?(:'cc')
        if (value = attributes[:'cc']).is_a?(Array)
          self.cc = value
        end
      end

      if attributes.key?(:'bcc')
        if (value = attributes[:'bcc']).is_a?(Array)
          self.bcc = value
        end
      end

      if attributes.key?(:'reply_to')
        if (value = attributes[:'reply_to']).is_a?(Array)
          self.reply_to = value
        end
      end

      if attributes.key?(:'text')
        self.text = attributes[:'text']
      end

      if attributes.key?(:'html')
        self.html = attributes[:'html']
      end

      if attributes.key?(:'body')
        self.body = attributes[:'body']
      end

      if attributes.key?(:'tags')
        if (value = attributes[:'tags']).is_a?(Array)
          self.tags = value
        end
      end

      if attributes.key?(:'headers')
        self.headers = attributes[:'headers']
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      end

      if attributes.key?(:'attachments')
        if (value = attributes[:'attachments']).is_a?(Array)
          self.attachments = value
        end
      end

      if attributes.key?(:'tracking')
        self.tracking = attributes[:'tracking']
      else
        self.tracking = nil
      end

      if attributes.key?(:'events')
        if (value = attributes[:'events']).is_a?(Array)
          self.events = value
        end
      else
        self.events = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn "[DEPRECATED] the `list_invalid_properties` method is obsolete"
      invalid_properties = Array.new
      if @message_id.nil?
        invalid_properties.push('invalid value for "message_id", message_id cannot be nil.')
      end

      if @channel_id.nil?
        invalid_properties.push('invalid value for "channel_id", channel_id cannot be nil.')
      end

      if @timestamp.nil?
        invalid_properties.push('invalid value for "timestamp", timestamp cannot be nil.')
      end

      if @mail_type.nil?
        invalid_properties.push('invalid value for "mail_type", mail_type cannot be nil.')
      end

      if @mail_source.nil?
        invalid_properties.push('invalid value for "mail_source", mail_source cannot be nil.')
      end

      if @delivery_type.nil?
        invalid_properties.push('invalid value for "delivery_type", delivery_type cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @subject.nil?
        invalid_properties.push('invalid value for "subject", subject cannot be nil.')
      end

      if @from.nil?
        invalid_properties.push('invalid value for "from", from cannot be nil.')
      end

      if @to.nil?
        invalid_properties.push('invalid value for "to", to cannot be nil.')
      end

      if @tracking.nil?
        invalid_properties.push('invalid value for "tracking", tracking cannot be nil.')
      end

      if @events.nil?
        invalid_properties.push('invalid value for "events", events cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn "[DEPRECATED] the `valid?` method is obsolete"
      return false if @message_id.nil?
      return false if @channel_id.nil?
      return false if @timestamp.nil?
      return false if @mail_type.nil?
      mail_type_validator = EnumAttributeValidator.new("String", [ "transactional", "broadcast" ])
      return false unless mail_type_validator.valid?(@mail_type)
      return false if @mail_source.nil?
      mail_source_validator = EnumAttributeValidator.new("String", [ "api", "smtp" ])
      return false unless mail_source_validator.valid?(@mail_source)
      return false if @delivery_type.nil?
      delivery_type_validator = EnumAttributeValidator.new("String", [ "live", "sandbox" ])
      return false unless delivery_type_validator.valid?(@delivery_type)
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new("String", [ "queued", "sent" ])
      return false unless status_validator.valid?(@status)
      return false if @subject.nil?
      return false if @from.nil?
      return false if @to.nil?
      return false if @tracking.nil?
      return false if @events.nil?
      true
    end

    # Attribute writer method
    # @param [Object] message_id Object to be assigned
    def message_id=(message_id)
      @message_id = message_id
    end

    # Attribute writer method
    # @param [Object] channel_id Object to be assigned
    def channel_id=(channel_id)
      @channel_id = channel_id
    end

    # Attribute writer method
    # @param [Object] timestamp Object to be assigned
    def timestamp=(timestamp)
      @timestamp = timestamp
    end

    # List of values valid for mail_type
    def self.mail_type_valid_values
    [ "transactional", "broadcast" ]
    end

    # Attribute writer method
    # @param [Object] mail_type Object to be assigned
    def mail_type=(mail_type)
      @mail_type = mail_type
    end

    # List of values valid for mail_source
    def self.mail_source_valid_values
    [ "api", "smtp" ]
    end

    # Attribute writer method
    # @param [Object] mail_source Object to be assigned
    def mail_source=(mail_source)
      @mail_source = mail_source
    end

    # List of values valid for delivery_type
    def self.delivery_type_valid_values
    [ "live", "sandbox" ]
    end

    # Attribute writer method
    # @param [Object] delivery_type Object to be assigned
    def delivery_type=(delivery_type)
      @delivery_type = delivery_type
    end

    # List of values valid for status
    def self.status_valid_values
    [ "queued", "sent" ]
    end

    # Attribute writer method
    # @param [Object] status Object to be assigned
    def status=(status)
      @status = status
    end

    # Attribute writer method
    # @param [Object] subject Object to be assigned
    def subject=(subject)
      @subject = subject
    end

    # Attribute writer method
    # @param [Object] from Object to be assigned
    def from=(from)
      @from = from
    end

    # Attribute writer method
    # @param [Object] to Object to be assigned
    def to=(to)
      @to = to
    end

    # Attribute writer method
    # @param [Object] cc Object to be assigned
    def cc=(cc)
      @cc = cc
    end

    # Attribute writer method
    # @param [Object] bcc Object to be assigned
    def bcc=(bcc)
      @bcc = bcc
    end

    # Attribute writer method
    # @param [Object] reply_to Object to be assigned
    def reply_to=(reply_to)
      @reply_to = reply_to
    end

    # Attribute writer method
    # @param [Object] text Object to be assigned
    def text=(text)
      @text = text
    end

    # Attribute writer method
    # @param [Object] html Object to be assigned
    def html=(html)
      @html = html
    end

    # Attribute writer method
    # @param [Object] body Object to be assigned
    def body=(body)
      @body = body
    end

    # Attribute writer method
    # @param [Object] tags Object to be assigned
    def tags=(tags)
      @tags = tags
    end

    # Attribute writer method
    # @param [Object] headers Object to be assigned
    def headers=(headers)
      @headers = headers
    end

    # Attribute writer method
    # @param [Object] metadata Object to be assigned
    def metadata=(metadata)
      @metadata = metadata
    end

    # Attribute writer method
    # @param [Object] attachments Object to be assigned
    def attachments=(attachments)
      @attachments = attachments
    end

    # Attribute writer method
    # @param [Object] tracking Object to be assigned
    def tracking=(tracking)
      @tracking = tracking
    end

    # Attribute writer method
    # @param [Object] events Object to be assigned
    def events=(events)
      @events = events
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          message_id == o.message_id &&
          channel_id == o.channel_id &&
          timestamp == o.timestamp &&
          mail_type == o.mail_type &&
          mail_source == o.mail_source &&
          delivery_type == o.delivery_type &&
          status == o.status &&
          subject == o.subject &&
          from == o.from &&
          to == o.to &&
          cc == o.cc &&
          bcc == o.bcc &&
          reply_to == o.reply_to &&
          text == o.text &&
          html == o.html &&
          body == o.body &&
          tags == o.tags &&
          headers == o.headers &&
          metadata == o.metadata &&
          attachments == o.attachments &&
          tracking == o.tracking &&
          events == o.events
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [ message_id, channel_id, timestamp, mail_type, mail_source, delivery_type, status, subject, from, to, cc, bcc, reply_to, text, html, body, tags, headers, metadata, attachments, tracking, events ].hash
    end

    # Outputs specified attributes and their values as a hash
    # @param [Array] attributes Attributes to include in hash
    # @return [Hash] Attribute/value-pairs of specified attributes
    def slice(*attributes)
      attributes.to_h do |attribute|
        [ attribute, public_send(attribute) ]
      end
    end

    # Allows hash-like assignment syntax for setting attributes
    # @param [Symbol, String] attribute The attribute name to set
    # @param [Object] value The value to assign
    def []=(attribute, value)
      public_send("#{attribute}=", value)
    end

    # Allows hash-like access to attributes
    # @param [Symbol, String] attribute The attribute name to get
    def [](attribute)
      public_send(attribute)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Helo.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
