=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require "date"
require "time"

module Helo
  class SendBroadcastRequest
    attr_accessor :from

    attr_accessor :reply_to

    attr_accessor :template

    attr_accessor :tracking

    attr_accessor :attachments

    attr_accessor :tags

    attr_accessor :headers

    attr_accessor :metadata

    attr_accessor :messages

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        'from': :'from',
        'reply_to': :'replyTo',
        'template': :'template',
        'tracking': :'tracking',
        'attachments': :'attachments',
        'tags': :'tags',
        'headers': :'headers',
        'metadata': :'metadata',
        'messages': :'messages'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        'from': :'MailAddress',
        'reply_to': :'Array<MailAddress>',
        'template': :'SendBroadcastRequestTemplate',
        'tracking': :'SendBroadcastRequestTracking',
        'attachments': :'Array<SendBroadcastRequestAttachmentsInner>',
        'tags': :'Array<String>',
        'headers': :'Object',
        'metadata': :'Object',
        'messages': :'Array<SendBroadcastRequestMessagesInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if !attributes.is_a?(Hash)
        fail ArgumentError, "The input argument (attributes) must be a hash in `Helo::SendBroadcastRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if !acceptable_attribute_map.key?(k.to_sym)
          fail ArgumentError, "`#{k}` is not a valid attribute in `Helo::SendBroadcastRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'from')
        self.from = attributes[:'from']
      else
        self.from = nil
      end

      if attributes.key?(:'reply_to')
        if (value = attributes[:'reply_to']).is_a?(Array)
          self.reply_to = value
        end
      end

      if attributes.key?(:'template')
        self.template = attributes[:'template']
      else
        self.template = nil
      end

      if attributes.key?(:'tracking')
        self.tracking = attributes[:'tracking']
      end

      if attributes.key?(:'attachments')
        if (value = attributes[:'attachments']).is_a?(Array)
          self.attachments = value
        end
      end

      if attributes.key?(:'tags')
        if (value = attributes[:'tags']).is_a?(Array)
          self.tags = value
        end
      end

      if attributes.key?(:'headers')
        self.headers = attributes[:'headers']
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      end

      if attributes.key?(:'messages')
        if (value = attributes[:'messages']).is_a?(Array)
          self.messages = value
        end
      else
        self.messages = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn "[DEPRECATED] the `list_invalid_properties` method is obsolete"
      invalid_properties = Array.new
      if @from.nil?
        invalid_properties.push('invalid value for "from", from cannot be nil.')
      end

      if @template.nil?
        invalid_properties.push('invalid value for "template", template cannot be nil.')
      end

      if @messages.nil?
        invalid_properties.push('invalid value for "messages", messages cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn "[DEPRECATED] the `valid?` method is obsolete"
      return false if @from.nil?
      return false if @template.nil?
      return false if @messages.nil?
      true
    end

    # Attribute writer method
    # @param [Object] from Object to be assigned
    def from=(from)
      @from = from
    end

    # Attribute writer method
    # @param [Object] reply_to Object to be assigned
    def reply_to=(reply_to)
      @reply_to = reply_to
    end

    # Attribute writer method
    # @param [Object] template Object to be assigned
    def template=(template)
      @template = template
    end

    # Attribute writer method
    # @param [Object] tracking Object to be assigned
    def tracking=(tracking)
      @tracking = tracking
    end

    # Attribute writer method
    # @param [Object] attachments Object to be assigned
    def attachments=(attachments)
      @attachments = attachments
    end

    # Attribute writer method
    # @param [Object] tags Object to be assigned
    def tags=(tags)
      @tags = tags
    end

    # Attribute writer method
    # @param [Object] headers Object to be assigned
    def headers=(headers)
      @headers = headers
    end

    # Attribute writer method
    # @param [Object] metadata Object to be assigned
    def metadata=(metadata)
      @metadata = metadata
    end

    # Attribute writer method
    # @param [Object] messages Object to be assigned
    def messages=(messages)
      @messages = messages
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          from == o.from &&
          reply_to == o.reply_to &&
          template == o.template &&
          tracking == o.tracking &&
          attachments == o.attachments &&
          tags == o.tags &&
          headers == o.headers &&
          metadata == o.metadata &&
          messages == o.messages
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [ from, reply_to, template, tracking, attachments, tags, headers, metadata, messages ].hash
    end

    # Outputs specified attributes and their values as a hash
    # @param [Array] attributes Attributes to include in hash
    # @return [Hash] Attribute/value-pairs of specified attributes
    def slice(*attributes)
      attributes.to_h do |attribute|
        [ attribute, public_send(attribute) ]
      end
    end

    # Allows hash-like assignment syntax for setting attributes
    # @param [Symbol, String] attribute The attribute name to set
    # @param [Object] value The value to assign
    def []=(attribute, value)
      public_send("#{attribute}=", value)
    end

    # Allows hash-like access to attributes
    # @param [Symbol, String] attribute The attribute name to get
    def [](attribute)
      public_send(attribute)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Helo.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
