=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require "date"
require "time"

module Helo
  class WebhookEvent
    ACCEPTED = "accepted".freeze
    PROCESSED = "processed".freeze
    CLICKED = "clicked".freeze
    OPENED = "opened".freeze

    def self.all_vars
      @all_vars ||= [ ACCEPTED, PROCESSED, CLICKED, OPENED ].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if WebhookEvent.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #WebhookEvent"
    end
  end
end
