=begin
#Helo API

#Helo API

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require "cgi"

module Helo
  class SuppressionsAPI
    attr_accessor :api_client

    def initialize(api_client = APIClient.default)
      @api_client = api_client
    end
    # Create suppressions
    # Adds email addresses to the suppression list to prevent future sends.
    # @param create_suppressions_request [CreateSuppressionsRequest]
    # @param [Hash] opts the optional parameters
    # @return [CreateSuppressionsResponse]
    def create(create_suppressions_request, opts = {})
      data, _status_code, _headers = create_with_http_info(create_suppressions_request, opts)
      data
    end

    # Create suppressions
    # Adds email addresses to the suppression list to prevent future sends.
    # @param create_suppressions_request [CreateSuppressionsRequest]
    # @param [Hash] opts the optional parameters
    # @return [Array<(CreateSuppressionsResponse, Integer, Hash)>] CreateSuppressionsResponse data, response status code and response headers
    def create_with_http_info(create_suppressions_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: SuppressionsAPI.create ..."
      end
      # verify the required parameter 'create_suppressions_request' is set
      if @api_client.config.client_side_validation && create_suppressions_request.nil?
        fail ArgumentError, "Missing the required parameter 'create_suppressions_request' when calling SuppressionsAPI.create"
      end
      # resource path
      local_var_path = "/suppressions"

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params["Accept"] = @api_client.select_header_accept([ "application/json" ]) unless header_params["Accept"]
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type([ "application/json" ])
      if !content_type.nil?
          header_params["Content-Type"] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(create_suppressions_request)

      # return_type
      return_type = opts[:debug_return_type]

      return_types_map = {
        200 => "CreateSuppressionsResponse",
        401 => "ErrorResponse",
        403 => "ErrorResponse",
        422 => "ErrorResponse",
        500 => "ErrorResponse"
      }

      # auth_names
      auth_names = opts[:debug_auth_names] || [ "bearerAuth" ]

      new_options = opts.merge(
        operation: :"SuppressionsAPI.create",
        header_params: header_params,
        query_params: query_params,
        form_params: form_params,
        body: post_body,
        auth_names: auth_names,
        return_type: return_type,
        return_types_map: return_types_map
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SuppressionsAPI#create\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List suppressions
    # Retrieves a list of suppressed email addresses for a channel.
    # @param channel_id [String]
    # @param mail_type [MailType]
    # @param [Hash] opts the optional parameters
    # @option opts [SuppressionReason] :reason
    # @option opts [String] :email
    # @option opts [Integer] :limit
    # @option opts [Integer] :offset
    # @return [PaginatedResponseOfSuppressionResponse]
    def list(channel_id, mail_type, opts = {})
      data, _status_code, _headers = list_with_http_info(channel_id, mail_type, opts)
      data
    end

    # List suppressions
    # Retrieves a list of suppressed email addresses for a channel.
    # @param channel_id [String]
    # @param mail_type [MailType]
    # @param [Hash] opts the optional parameters
    # @option opts [SuppressionReason] :reason
    # @option opts [String] :email
    # @option opts [Integer] :limit
    # @option opts [Integer] :offset
    # @return [Array<(PaginatedResponseOfSuppressionResponse, Integer, Hash)>] PaginatedResponseOfSuppressionResponse data, response status code and response headers
    def list_with_http_info(channel_id, mail_type, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: SuppressionsAPI.list ..."
      end
      # verify the required parameter 'channel_id' is set
      if @api_client.config.client_side_validation && channel_id.nil?
        fail ArgumentError, "Missing the required parameter 'channel_id' when calling SuppressionsAPI.list"
      end
      # verify the required parameter 'mail_type' is set
      if @api_client.config.client_side_validation && mail_type.nil?
        fail ArgumentError, "Missing the required parameter 'mail_type' when calling SuppressionsAPI.list"
      end
      if @api_client.config.client_side_validation && !opts[:'limit'].nil? && opts[:'limit'] > 500
        fail ArgumentError, 'invalid value for "opts[:"limit"]" when calling SuppressionsAPI.list, must be smaller than or equal to 500.'
      end

      if @api_client.config.client_side_validation && !opts[:'limit'].nil? && opts[:'limit'] < 1
        fail ArgumentError, 'invalid value for "opts[:"limit"]" when calling SuppressionsAPI.list, must be greater than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'offset'].nil? && opts[:'offset'] < 0
        fail ArgumentError, 'invalid value for "opts[:"offset"]" when calling SuppressionsAPI.list, must be greater than or equal to 0.'
      end

      # resource path
      local_var_path = "/suppressions"

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'channelId'] = channel_id
      query_params[:'mailType'] = mail_type
      query_params[:'reason'] = opts[:'reason'] if !opts[:'reason'].nil?
      query_params[:'email'] = opts[:'email'] if !opts[:'email'].nil?
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      query_params[:'offset'] = opts[:'offset'] if !opts[:'offset'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params["Accept"] = @api_client.select_header_accept([ "application/json" ]) unless header_params["Accept"]

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      return_types_map = {
        200 => "PaginatedResponseOfSuppressionResponse",
        401 => "ErrorResponse",
        403 => "ErrorResponse",
        422 => "ErrorResponse",
        500 => "ErrorResponse"
      }

      # auth_names
      auth_names = opts[:debug_auth_names] || [ "bearerAuth" ]

      new_options = opts.merge(
        operation: :"SuppressionsAPI.list",
        header_params: header_params,
        query_params: query_params,
        form_params: form_params,
        body: post_body,
        auth_names: auth_names,
        return_type: return_type,
        return_types_map: return_types_map
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SuppressionsAPI#list\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Remove suppressions
    # Removes email addresses from the suppression list to allow future sends.
    # @param remove_suppressions_request [RemoveSuppressionsRequest]
    # @param [Hash] opts the optional parameters
    # @return [RemoveSuppressionsResponse]
    def remove(remove_suppressions_request, opts = {})
      data, _status_code, _headers = remove_with_http_info(remove_suppressions_request, opts)
      data
    end

    # Remove suppressions
    # Removes email addresses from the suppression list to allow future sends.
    # @param remove_suppressions_request [RemoveSuppressionsRequest]
    # @param [Hash] opts the optional parameters
    # @return [Array<(RemoveSuppressionsResponse, Integer, Hash)>] RemoveSuppressionsResponse data, response status code and response headers
    def remove_with_http_info(remove_suppressions_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: SuppressionsAPI.remove ..."
      end
      # verify the required parameter 'remove_suppressions_request' is set
      if @api_client.config.client_side_validation && remove_suppressions_request.nil?
        fail ArgumentError, "Missing the required parameter 'remove_suppressions_request' when calling SuppressionsAPI.remove"
      end
      # resource path
      local_var_path = "/suppressions/remove"

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params["Accept"] = @api_client.select_header_accept([ "application/json" ]) unless header_params["Accept"]
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type([ "application/json" ])
      if !content_type.nil?
          header_params["Content-Type"] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(remove_suppressions_request)

      # return_type
      return_type = opts[:debug_return_type]

      return_types_map = {
        200 => "RemoveSuppressionsResponse",
        401 => "ErrorResponse",
        403 => "ErrorResponse",
        422 => "ErrorResponse",
        500 => "ErrorResponse"
      }

      # auth_names
      auth_names = opts[:debug_auth_names] || [ "bearerAuth" ]

      new_options = opts.merge(
        operation: :"SuppressionsAPI.remove",
        header_params: header_params,
        query_params: query_params,
        form_params: form_params,
        body: post_body,
        auth_names: auth_names,
        return_type: return_type,
        return_types_map: return_types_map
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SuppressionsAPI#remove\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
